
[package]
name = "udon"
version = "0.1.0"
authors = ["Hajime Suzuki <suzuki.hajime.s@gmail.com>"]
edition = "2018"

[dependencies]
bitfield = "0.13"
log = "0.4"


[[example]]
name = "ribbon"
crate-type = ["bin"]

[dev-dependencies]
bam = "0.1"
env_logger = "0.7"
image = "0.23"
structopt = "0.3"

